version: 0.2

env:
  variables:
    ARTIFACT_BUCKET: "cloudx-pipeline-artifacts-bucket2"
    REGION: "ap-south-1"

phases:
  install:
    runtime-versions:
      dotnet: 8.0
    commands:
      - echo "Installing AWS SAM CLI"
      - pip install aws-sam-cli

  build:
    commands:
      - echo "Restoring .NET dependencies"
      - dotnet restore
      - echo "Building project"
      - sam build
      - echo "Validating SAM template"
      - sam validate --template-file template.yaml
      - echo "Packaging SAM template"
      - sam package \
        --template-file template.yaml \
        --output-template-file packaged.yaml \
        -- s3-bucket cloudx-pipeline-artifacts-bucket2
      - echo "Listing contents after sam package:"
      - ls -la

artifacts:
  files:
    - '**/*'