version: 0.2

env:
  variables:
    ARTIFACT_BUCKET: "cloudx-pipeline-artifacts-bucket"
    REGION: "ap-south-1"

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install aws-sam-cli
  build:
    commands:
      - sam build
      - sam package \
          --template-file template.yaml \
          --output-template-file packaged.yaml \
          --s3-bucket $ARTIFACT_BUCKET \
          --region $REGION

artifacts:
  files:
    - packaged.yaml
